[pytest]
testpaths = notes/pytest_tests
DJANGO_SETTINGS_MODULE = yanote.settings
norecursedirs = env/*
; addopts = -rE -vv --show-capture=no --disable-warnings -p no:cacheprovider
python_files = test_*.py
django_debug_mode = true
